name: Automated Tests

on: pull_request

jobs:
  vitest:
    name: Vitest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.20.5

      - name: Create .env file
        run: |
          echo "POSTGRES_USER: ${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}" >> .env
          echo "DATABASE_URL: ${{ secrets.DATABASE_URL }}" >> .env
          echo "NODE_ENV: ${{ secrets.NODE_ENV }}" >> .env

      - run: ls

      - run: npm ci

      - run: npm test
